### ISSUE TITLE
特殊的模块名是否会带来问题？

### ISSUE THREAD

**Issue by rprx** [2dust/AndroidLibXrayLite#1]
比如 `github.com/xtls/xray-core/v1` 的 `v1`

**Comment by 2dust** [comment]
使用go get github.com/xtls/xray-core 拉下来的源码中是没有/v1的

**Comment by rprx** [comment]
哪个比较方便？如果不带 `v1` 更方便，下个版本就改
因为有人提到了这个问题 https://github.com/XTLS/Xray-core/issues/6 ，可能是在他在编译 Kitsunebi 时遇到的

**Comment by 2dust** [comment]
不带v1在编译的时候更方便,不过这个不影响大局,手工mv到v1下面就可以了.
只要和v2ray-core的兼容就不需要改动上层实现,可以无损换core

**Comment by 2dust** [comment]
如果能移除v1是方便些.
版本可以使用branch,也可以再开一个项目

**Comment by rprx** [comment]
好的，下个版本就移除 `v1`
配置上打算始终兼容，可能还会有 API 名称的兼容

题外话：v2rayN 可否加上检测 xray.exe，感谢！

**Comment by rurirei** [comment]
`go get` is deprecated.

**Comment by rurirei** [comment]
env name needs changed. https://github.com/2dust/AndroidLibXrayLite/blob/25c4a94ee7ada79218770cf5926217eb8d92cb70/interact.go#L33

**Comment by rprx** [comment]
Xray-core v1.1.0+，已去除包名中的 `v1`。
