### ISSUE TITLE
I need last version of libv2ray.aar

### ISSUE THREAD

**Issue by visaping** [2dust/AndroidLibXrayLite#15]
I need the latest version of the libv2ray.aar library
I saw how to set up this library, but I could not get an output from it
Please send me the new version.
Thanks
My email address is: [jackjustin31999@gmail.com](mailto:jackjustin31999@gmail.com)

**Comment by kordavpn** [comment]
Yes, we all need reality :)

**Comment by SadraRahmani** [comment]
https://github.com/hiddify/HiddifyNG/blob/master/V2rayNG/app/libs/libv2ray.aar
see if this works

**Comment by visaping** [comment]
thanks alot

‫‪SadraRahmani‬‏ ***@***.***‬‏> در تاریخ پنجشنبه ۴ مه ۲۰۲۳
ساعت ۱۳:۳۴ نوشت:‬
