### ISSUE TITLE
Reality not working when using 1.8.0 XrayCore

### ISSUE THREAD

**Issue by SadraRahmani** [2dust/AndroidLibXrayLite#16]
Hello
When I Bind this project using gomobile and include .aar in V2rayNG forked android application, all configs work except for reality
![image](https://user-images.githubusercontent.com/19726427/234361791-d0f8a3ee-0fd0-43e1-a2b1-c8bcc1bcf82d.png)

More specifically it sometimes work when reality config has ip instead of domain, but never with a domain(pointing to that ip ofcourse)

![image](https://user-images.githubusercontent.com/19726427/234362855-b17fb37e-0a59-422d-8130-61df097663d7.png)

I noticed the main v2rayng 1.8.3 application itself does not have this issue and all reality configs work fine in it

**Comment by yxiangTang** [comment]
same，how to solve

**Comment by MohammadRezaei92** [comment]
I have same issue

**Comment by mromidi** [comment]
same issue, please provide a solution
