### ISSUE TITLE
Vless does'nt work

### ISSUE THREAD

**Issue by AlirezaIvaz** [2dust/AndroidLibXrayLite#17]
I built both xray core and v2fly core but vless and trojan not works with them in v2rayNG app.
I meant my built of v2rayNG not it's official version. In the official version of v2rayNG my configurations works properly but when I build it with android studio, only VMess works properly.
I built v2rayNG v1.8.4 with xray core v1.8.1, also I used Go 1.20.3 in Ubuntu 20.04 for building xray core.
Do you have any idea?

**Comment by naderghazidev** [comment]
@AlirezaIvaz did you find a solution for this?
