### ISSUE TITLE
Problem with android ndk

### ISSUE THREAD

**Issue by armanTabib** [2dust/AndroidLibXrayLite#21]
I'm trying to build the library in order to make a client for v2ray protocols.
I follow build instructions and at the last step I get the follwoing error: 
```
gomobile: no usable NDK in /home/X/Android/Sdk: open /home/X/Android/Sdk/ndk/wrap.sh/meta/platforms.json: no such file or directory, open /home/X/Android/Sdk/ndk-bundle/meta/platforms.json: no such file or directory
```
my `/home/X/Android/Sdk/ndk/wrap.sh` directory contains only one file `asan.sh`. 
Should I do anything extra with the NDK?

**Comment by helgesander** [comment]
When I had this problem, I changed the name of the ndk directory to ndk-bundle. It should work if you have the right API version
