### ISSUE TITLE
Is it possible to build this library for iOS?

### ISSUE THREAD

**Issue by pavel-vorobyev** [2dust/AndroidLibXrayLite#23]
Hello. Is it possible to build this library for iOS? In theory this is possible, I can simply change the parameters of the `gomobile` command to build for iOS. But will it work?

**Comment by ghostwolf90** [comment]
Compiling into an iOS Framework is feasible, please use the following command. However, I am not clear on how to use it after compilation.

gomobile bind -v -target=ios -o XrayKit.xcframework -ldflags='-s -w' ./
