### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by atomixgroup** [2dust/AndroidLibXrayLite#26]
[i have same errors.](gomobile: go build -v -ldflags -s -w -buildmode=c-shared -o=/tmp/gomobile-work-3324249495/android/src/main/jniLibs/x86_64/libgojni.so ./gobind failed: exit status 1)

**Comment by lgl772384055** [comment]
git clone https://github.com/2dust/AndroidLibXrayLite.git
vi go.mod
修改  github.com/xtls/xray-core v1.8.4

然后就能编译了

**Comment by kaitoKing** [comment]
> git clone https://github.com/2dust/AndroidLibXrayLite.git vi go.mod 修改 github.com/xtls/xray-core v1.8.4
> 
> 然后就能编译了

感谢大佬，确实修改成1.8.4之后就没有这个问题了，但是修改成1.8.3和1.8.1之后就还是会出现这个问题，想请问下大佬，知道是什么原因嘛？如果想要编译1.8.3该如何修改呢
