### ISSUE TITLE
Error after update and build

### ISSUE THREAD

**Issue by AC-Lover** [2dust/AndroidLibXrayLite#27]
Hello
I have built it now, but I encounter the following error in Android Studio, please help

![image](https://github.com/2dust/AndroidLibXrayLite/assets/49290111/b7596851-6b11-47d5-9ea5-8689b23bb999)

libv2ray.aar :
https://drive.google.com/file/d/19jccYpW7U5k2DWt-bWSRWc4zFBBTxYWL/view?usp=sharing

**Comment by burce538** [comment]
@AC-Lover 
我遇到了跟你一样的问题，jdk版本从21降到17，然后go clean -cache清理缓存，再重新编译就可以替换打包了
