### ISSUE TITLE
编译后运行错误

### ISSUE THREAD

**Issue by chijiao** [2dust/AndroidLibXrayLite#47]
编译正常,版本号 Lib v26, Xray-core v1.8.10. 运行时, 报错

setUpListener => new initialize from V2rayVPNService
panic: xray.xudp.basekey: invalid value (BaseKey must be 32 bytes): W5kcm9pZF9pZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= len 30

**Comment by omid-the-great** [comment]
This problem probably occurs when using the `InitV2Env` function. The error is quite clear, **the length of the second argument must be 32 bytes**

If you develope your own program visit [this](https://github.com/2dust/v2rayNG/blob/6da988e3db2751f3ad1f3eb65de800d77ef80969/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/Utils.kt#L328) link

anyway It doesn't seem to be a problem with the library and this problem probably occurs when you use the library
