### ISSUE TITLE
Are there any example or tutorial?

### ISSUE THREAD

**Issue by 250king** [2dust/AndroidLibXrayLite#54]
I want to use the library to set up the connection to my server. I have google the library but there's less about the library. Could the project owner show some example or tutorial? Thanks!

**Comment by 4121nnn** [comment]
I need  example too, can someone show the simple example how to use it

**Comment by 250king** [comment]
I know how to use the library and have integrated with my project successfully.
In fact, there are less documents about this so it took me a lot of time to do research. I will write an article to introduce it.

**Comment by maleeqB** [comment]
Hi @250king please have you posted the guide? and please can you share the link? Thank you

**Comment by SidMorad** [comment]
You could see an example of usage of this library at here:
https://github.com/2dust/v2rayNG

You need to copy the `libv2ray.aar` at following directory:
https://github.com/2dust/v2rayNG/tree/master/V2rayNG/app/libs

I believe you could use this library for iOS too, and please share your link here if you find any example, thanks.
