### ISSUE TITLE
Error after start service

### ISSUE THREAD

**Issue by orginweb** [2dust/AndroidLibXrayLite#55]
After latest update of v2rayng android I have created aar file with your repo
but when I click on connect button, it throws error and service stops after 1 second and it doesn't connect at all, Here are the logs in Android Studio:
AndroidLibXrayLite/libv2ray_main.go:101 +0x210 fp=0x4000529de0 sp=0x4000529d60 pc=0x7b0239d2c0
AndroidLibXrayLite/libv2ray_main.go:164 +0x450 fp=0x4000529d60 sp=0x4000529c70 pc=0x7b0239ddb0

**Comment by karlovm** [comment]
same issue.

**Comment by karlovm** [comment]
For everyone else facing this problem: I figured out that arm64-v8a not working with .so library, but armeabi-v7a works well on all of my testing devices.
